openapi: 3.0.3
info:
  title: L1 Connectivity Service Schema - Test API
  version: 1.0.0
  description: Simple OAS Test API that can be used to test the L1 Connectivity Service schema validity with OpenAPI Generator tool as well as to generate markdown documentation and plantuml diagrams
paths:
  '/l1Enni':
    get:
      operationId: l1Enni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1Enni.yaml'
  '/l1OperatorUni':
    get:
      operationId: l1OperatorUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1OperatorUni.yaml'
  '/l1SubscriberUni':
    get:
      operationId: l1SubscriberUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1SubscriberUni.yaml'
  '/l1SubscriberVc':
    get:
      operationId: l1SubscriberVc
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1SubscriberVc.yaml'
  '/l1OperatorVc':
    get:
      operationId: l1OperatorVc
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1OperatorVc.yaml'
  '/l1Sls':
    get:
      operationId: l1Sls
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'l1Sls.yaml'