openapi: 3.0.0
paths: {}
x-schema: http://json-schema.org/draft-07/schema#
x-mef-id: urn:mef:lso:spec:legato:ip-fault-management-results:v0.0.1:all
info:
  description: IP Fault Management Results schema.
  title: 
    MEF LSO Legato - IP Fault Management Results
    # MEF Forum - Date: 20230404  Edit-level: 
    # File: ip/faultAndPerformanceManagement/ipFaultManagementResults.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # © MEF Forum 2023. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
  version: 0.0.1
components:
  schemas:
    IpPacketErrorStatistics:
      description: The IP Packet receive statistics on an interface or VLAN.
      type: object
      properties:
        interface:
          type: string
        vlan:
          type: integer
        startTime:
          format: date-time
          type: string
        endTime:
          format: date-time
          type: string
        inHeaderErrors:
          description: >-
            The number of packets received by this IP instance and then discarded because of 
            IP headers errors. These error types include checksum and format errors, version 
            number and option mismatch, and TTL count expiration.
          type: integer
        inAddressErrors:
          description: The number of packets received by this IP instance and then discarded because of an invalid address or unsupported class in the IP header.
          type: integer
        unknownProtocols:
          description: The number of packets received by this IP instance and then discarded because the protocol was unknown or unsupported.
          type: integer
        outDiscards:
          description: The number of outbound packets received by this IP instance for transmission and then discarded even though the packet was received without error. Reasons for discard include queue overflow and buffer problems.
          type: integer
        outNoRoutes:
          description: The number of outbound IP packets that were not forwarded on to their destination because no route could be found.
          type: integer
        reassemblyTimeouts:
          description: The number of timeouts that occurred when attempting to reassemble IP fragments because all fragments were not received.
          type: integer
        reassembliesRequired:
          description: The total number of fragments received by this IP instance that required reassembly.
          type: integer
        reassembliesFailed:
          description: The number of reassembly failures detected by the IP re-assembly algorithm on this IP instance.
          type: integer
        fragmentsOk:
          description: The number of IP packets that this IP instance has successfully fragmented. See the Fragments Created argument for a count of total fragments generated.
          type: integer
        fragmentsFailed:
          description: The number of IP packets that this IP instance was not able to fragment even though the packet required it. This could be the result of a dontFrag bit setting.
          type: integer
        fragmentsCreated:
          description: The total number of fragments created by this IP instance in the fragmentation process. See the Fragments OK argument for a count of total packets fragmented.
          type: integer
        badIpChecksums:
          description: The total number of packets dropped because they were received with a bad IP checksum.
          type: integer
        droppedFragments:
          description: The total number of fragmented packets that were dropped because there were no reassembly resources available.
          type: integer
        completedPacketsBad:
          description: The total number of fragmented packets that were dropped after reassembly because they exceeded the maximum packet size supported by the system.
          type: integer
        completedPacketDropped:
          description: The total number of fragmented packets that were dropped after reassembly because they exceeded the maximum packet size supported by the system.
          type: integer
        incompletePacketsTimeout:
          description: The total number of fragmented packets that were dropped because the reassembly timeout expired before all fragments were received.
          type: integer
    IpvcEndPoint:
      description: A subclass of a SlsReferencePoint.
      properties:
        id:
          description: IPVC End Point unique identifier
          type: string
        description:
          description: IPVC End Point description
          type: string
      type: object
    Location:
      allOf:
        - $ref: '#/components/schemas/SlsReferencePoint'
        - description: A subclass of a SlsReferencePoint.
          properties:
            ipvcEndpoint:
              description: Pointer to IPVC End Point
              items:
                type: string
              type: array
            name:
              description: Location name
              type: string
            description:
              description: Location description
              type: string
            cloudService:
              description: Attribute to indicate if associated with a cloud service.
              type: boolean
          type: object
      type: object
    SlsReferencePoint:
      oneOf:
        - $ref: '#/components/schemas/Location'
        - $ref: '#/components/schemas/IpvcEndPoint'
        - description: SlsReferencePoint is an abstract data type that can be subclassed to IpvcEndPoint and Location. Reference MEF 61.1 Section 10.9.1 SLS Reference Points.
          type: object
    SlsRpPair:
      description: Service Level Specification Reference Point Pair. In a multipoint or rooted multipoint IPVC, performance objectives are ideally specified as applying between pairs of IPVC EPs - in other words, they apply to the performance that IP Data Packets experience as they flow from one EI to another. The SlsRpPair is a representation of this association. Reference MEF 61.1 Section 10.9.1
      properties:
        fromSlsReferencePoint:
          $ref: '#/components/schemas/SlsReferencePoint'
        toSlsReferencePoint:
          $ref: '#/components/schemas/SlsReferencePoint'
      type: object
    TimeDuration:
      description: This class is used to describe durations expressed as a 2-tuple, (value, units). The units from from nanoseconds to years.
      properties:
        timeDurationValue:
          description: The value of the duration. For example, if the duration is 20 ms, this element is 20.
          type: integer
        timeDurationUnits:
          $ref: '#/components/schemas/TimeDurationUnits'
      type: object
    TimeDurationUnits:
      description: |-
        The unit of measure in the duration. For example, if an interval is 2ms, this element is MS.
      enum:
        - NS
        - US
        - MS
        - SEC
        - MIN
        - HOUR
        - DAY
        - WEEK
        - MONTH
        - YEAR
      type: string
    TimePeriod:
      description: A period of time, either as a deadline (endDateTime only) a startDateTime only, or both
      properties:
        startDateTime:
          description: Start of the time period, using IETC-RFC-3339 format
          example: '1985-04-12T23:20:50.520Z'
          format: date-time
          type: string
        endDateTime:
          description: End of the time period, using IETC-RFC-3339 format
          example: '1985-04-12T23:20:50.520Z'
          format: date-time
          type: string
      type: object